#!/usr/bin/env python3
import sys
import os

args = sys.argv[1:]
parents = False
dirs = []

for arg in args:
    if arg == '-p':
        parents = True
    else:
        dirs.append(arg)

if not dirs:
    print("rmdir: missing operand", file=sys.stderr)
    sys.exit(1)

for d in dirs:
    try:
        if parents:
            # Remove directory and parents
            path = d.rstrip('/')
            while path:
                os.rmdir(path)
                path = os.path.dirname(path)
        else:
            os.rmdir(d)
    except Exception as e:
        print(f"rmdir: {d}: {e}", file=sys.stderr)
        sys.exit(1)

sys.exit(0)
